### ISSUE TITLE
The executable .... BRLMPrinterKit' contains Bitcode

### ISSUE THREAD

**Issue by bapla6** [CodeMinion/another_brother#101]
Hi, thanks for your wonderful package, which works perfectly on android, but IOS is pretty painful.
![image](https://github.com/user-attachments/assets/6f9323e1-ac1a-44b4-bd89-8557486c31fb)

I followed your instructions on youtube, the build succeeds as well, but whenever i try to upload the app to testflight, I am stucked with the following errors:

1. The executable BLRMPrinterKit contains Bitcode
...

Do you have any suggestions?

Thx

**Comment by bapla6** [comment]
Hi, I tried to use the ios-no-type-b branch. and no I'm stuck with the next error:  


This expression has type 'void' and can't be used.
Flutter BluePlus flutterBlue=FlutterBluePlus.instance


   // TODO Consider moving this to iOS side.
    if (Platform.isIOS) {
      //BLE Scanning
      FlutterBluePlus flutterBlue = FlutterBluePlus.instance;

      // Start scanning
      flutterBlue.startScan(withServices: [Guid("A76EB9E0-F3AC-4990-84CF-3A94D2426B2B")], timeout: Duration(seconds: timeout~/1000));

      Set<BLEPrinter> foundDevices = {};
      // Listen to scan results
      var subscription = flutterBlue.scanResults.listen((results) {
        for (ScanResult r in results) {
          BLEPrinter found = BLEPrinter(localName: r.device.name);
          if (!foundDevices.contains(found)) {
            foundDevices.add(found);
          }
        }
      });

      return await Future.delayed(Duration(seconds: timeout~/1000), () => foundDevices.toList());
    }

**Comment by PrimaelQuemerais** [comment]
Hi @bapla6,

I ran into the same issue, just add this to your Podfile :

```
post_install do |installer|
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end
    
    framework_paths = [
      "Pods/BRLMPrinterKit_AB/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit",
    ]
    
    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
    
    installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
end
```

I was able to build and deliver through TestFlight after this.

**Comment by CodeMinion** [comment]
Thanks for the support @PrimaelQuemerais!

**Comment by bapla6** [comment]
Thank you @CodeMinion and @PrimaelQuemerais , app is running now :)
