### ISSUE TITLE
use another_brother in IOS simulator

### ISSUE THREAD

**Issue by BentEngbers** [CodeMinion/another_brother#11]
Is it possible to use this library in the IOS simulator? It works on a physical device, but when i try to run it in the simulator, it gives the following error:

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file 'PROJECT_DIRECTORY/ios/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by CodeMinion** [comment]
Hi @BentEngbers ,

Thanks for the question. Unfortunately using it in the Simulator is not  due to some missing binary, but I can't remember the specifics of why. Deploying to an actual device will work. 

Thanks again,

**Comment by BentEngbers** [comment]
Thanks for the help!
