### ISSUE TITLE
Not working on M1?

### ISSUE THREAD

**Issue by vitorhpereira** [CodeMinion/another_brother#13]
Hi there,

I got this error trying to build:
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/vitor/StudioProjects/myapp1/ios/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit' for architecture arm64

Any chance to work on arm64 arc?

Thanks!

**Comment by CodeMinion** [comment]
Hi @vitorhpereira ! 

Thanks for reaching out about this and apologies for the late repossess, thought I had. As for M1 support yes works on M1 however the another_borhter as as whole will not work on the emulator.

Thanks again for reaching out!
