### ISSUE TITLE
Build M1

### ISSUE THREAD

**Issue by elninho22** [CodeMinion/another_brother#17]
hello Mr @CodeMinion 
I'm having problems Build on Xcode MAC M1, I get these logs:
Treatments: added config in Xcode another_brother = required
Used another_brother:
     git:
      url: git://github.com/CodeMinion/another_brother.git
      ref: ios-no-type-b
unsuccessfully

logs:
ld: warning: ignoring file /Users/andre/Library/Developer/Xcode/DerivedData/Runner-abfcsgvdhwjizuccyqtvfwgolllg/Build/Products/Debug-iphonesimulator/BROTHERSDK/BROTHERSDK.framework/BROTHERSDK, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/andre/Documents/Projetos/4.events-app/ios/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Messages
Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/andre/Documents/Projetos/4.events-app/ios/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit' for architecture arm64

Showing Recent Messages
Ignoring file /Users/andre/Library/Developer/Xcode/DerivedData/Runner-abfcsgvdhwjizuccyqtvfwgolllg/Build/Products/Debug-iphonesimulator/BROTHERSDK/BROTHERSDK.framework/BROTHERSDK, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

Thanks

**Comment by CodeMinion** [comment]
Hello @elninho22 ,

Thanks for reaching out about this. I see from the logs that you are tying to deploy to the simulator. Currently the simulator is not support of iOS so you'll need to build to a physical device instead. 

Hope this helps but please don't hesitate to reach out if you run into any other issues,
