### ISSUE TITLE
Compatibility with emulator IOS

### ISSUE THREAD

**Issue by elninho22** [CodeMinion/another_brother#18]
Hi Mr Frank.

Do you have a project to make another brother compatible with emulator IOS, or how we can help to achieve it?

thank you very much for your project! it's perfect

**Comment by CodeMinion** [comment]
Hi @elninho22 !

Thanks for reaching out about this and for the offer! If I remember correctly the limitation lie in the iOS binary that another_brother uses. These come from Brother and I do hear they have an update so there is a chance this has been resolved in the newer version. I'll find out more during the Brother Hackathon this year and post an update here as I find out more. 

Thanks again!
