### ISSUE TITLE
App rejected in IOS Store

### ISSUE THREAD

**Issue by xncz8h** [CodeMinion/another_brother#19]
## Problem
Me and my colleagues are trying to publish our app in the IOS store however we've run into a issue. Apple claims that our app is not authorized by the accessory manufacturer to work with the following MFI accessory:

- com.brother.ptcbp
- com.issc.datapath

Also see the contents of the email below of the rejection email.

## Solutions Tried
Although we already applied for the MFi Product Plan ID (PPID) through brothers [website](https://secure6.brother.co.jp/mfi/Top.aspx) it is still not approved due to the same reasons.

## Our Request
Since these two packages are required by this library, we were wondering how to solve this problem. We know this is possible since there are other apps with this packages already successfully released. For any hints we would be extremely greatful.

### Rejection email
Thank you for providing the following information.

However, your app has not been authorized by the accessory manufacturer to work with the MFi accessory.

- com.brother.ptcbp
- com.issc.datapath

Next Steps

To resolve this issue, please contact the accessory manufacturer to request your app be added to the MFi Product Plan form.

When we receive your reply with this confirmation, we can proceed with the review. We do not require a new binary.

If you have not yet provided the accessory's MFi Product Plan ID (PPID), please enter this information in the Notes section for your app in App Store Connect. If you do not know the PPID, please request this information from the accessory manufacturer.

To edit the Notes section:

Log in to App Store Connect
Click on "My Apps"
Select your app
Click on the app version on the left side of the screen
Scroll down to "App Review Information"
Update "Notes"
Click "Save"
Once you've completed all changes, click the "Submit for Review" button at the top of the App Version Information page.

**Comment by CodeMinion** [comment]
Hello @xncz8h , 

Thanks for reaching out about this. Yes, you will need to receive that PPID from Brother though not sure how long the exact turnaround time for that application is. 

That said the Brother Hackathon registration is open for this year. This will give you a chance to chat with some of the Brother engineers and Managers directly so you might be able to get a direct answer from them if you drop by: https://brotherhackathon.com/

Hope to see you there,

**Comment by xncz8h** [comment]
Hey @CodeMinion , 

Thank you for that response. We resolved the issue with the com.brother.ptcbp package through the PPID form through Brother. However, our app is still refused due to the second package this library uses: com.issc.datapath.

Any thoughts on how to resolve this issue?

**Comment by CodeMinion** [comment]
Hey @xncz8h ! 

Glad to hear you got the PPID issue resolved. I am not really sure what the requirements for Apple's com.issc.datapath are but I'll ask the Brother folks during the hackathon and let you know.

Thanks again for reaching out about this,

**Comment by shobhit14gupta** [comment]
> Hey @xncz8h !
> 
> Glad to hear you got the PPID issue resolved. I am not really sure what the requirements for Apple's com.issc.datapath are but I'll ask the Brother folks during the hackathon and let you know.
> 
> Thanks again for reaching out about this,

I also faced the same issue. I got the PPID from Brother to resolve issue with com.brother.ptcbp package, but app still rejected due to second package "com.issc.datapath".  Any update to resolve this issue?

**Comment by CodeMinion** [comment]
Hey @shobhit14gupta ! 

Thanks for reaching out about this and sorry to hear you are also facing the same issue. I checked with some of the Brother folks during the last hackathon and they were not sure about "com.issc.datapath" either. This should be in your plist to be able to connect to accessories over Bluetooth. 

But have you tried not including it to see if you can still print? 

Thank agin for reaching out!

**Comment by Andre-Coelhoo** [comment]
I have the same problem, any solution?

**Comment by CodeMinion** [comment]
Hi @Andre-Coelhoo , 

Thanks for reaching out about this. Would you be able to provide the recent the Apple store gave you for the rejection?

Thanks in advance,
