### ISSUE TITLE
ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by twin250** [CodeMinion/another_brother#20]
Hello. Thank you for this plugin I have been having some fun with it today!

I have an issue with sending a file to my brother printer (model TD-4550DNWB). I have successfully been able to send a paragraph to it. When I try and send a .prn file I get the error ERROR_FILE_NOT_FOUND. I have loaded the asset into my yaml file and included it within the asset folder. I am testing this on my iPad. 

Any assistance with this is greatly appreciated

**Comment by CodeMinion** [comment]
Hello @twin250 ,

Thanks for reaching out about this. Could you share the code you are using to send the file to the printer?

Thanks in advance!

**Comment by twin250** [comment]
Hello. Getting the same error on my QL_820NWB. I have connected the devices on my network to test from my iPad. This is my code:

    var printer = new Printer();
    List<NetPrinter> netPrinters =
    await printer1.getNetPrinters([Model.QL_820NWB.getName()]);
    print("Net Printers Found: $netPrinters");
    PrinterInfo printerInfo = PrinterInfo(
    port: Port.NET,
    printerModel: Model.QL_820NWB,
    ipAddress: netPrinters[0].ipAddress,
    macAddress: netPrinters[0].macAddress);
    printerInfo.printMode = PrintMode.ORIGINAL;
    printerInfo.isAutoCut = true;
    printerInfo.numberOfCopies = 1;

    await printer.setPrinterInfo(printerInfo);

    PrinterStatus status = PrinterStatus();
    bool success = await printer.startCommunication();
    print("Connected to printer? $success");
    print('calling print file');
    status = await printer.printFile('assets/label.prn');
    success = await printer.endCommunication();
    print('closed print communication $success');

pubspec.yaml:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/9248514/156343509-faccb066-a325-4bad-ace6-33735cfde0d0.png">

assets folder:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/9248514/156343631-73ffd02e-cf6f-44ff-b038-684a3919eb48.png">

Thanks again!

**Comment by CodeMinion** [comment]
Thanks for the code @twin250 ! 

At a glance I believe the problem is that you are passing asset path. Print file requires the full path to the file being printed so you might need to first save the asset to a temp file and then path the path to that temp file to printFile.

**Comment by twin250** [comment]
Thank you for your help. I have changed it to use FilePicker. The return status gives me ERROR_NONE but the printer does not print the file. I don't know if it's related to the set printer info. I will keep testing!

**Comment by CodeMinion** [comment]
Glad to hear it helped @twin250 . 

It might not be the issue but in the past I have noticed that if you call endCommunication before the printing begins it never prints. Have you tried making the call without calling endCommunication?

**Comment by twin250** [comment]
Hello @CodeMinion,

I have tried sending the file prints back to the TD-4550DNWB printer. It looks like it is doing something as the printer's LCD screen says "receiving" but nothing prints. I have tried taking out endCommunication. Hopefully, it's a setting I have overlooked.
