### ISSUE TITLE
QL_720NW Printer not discovered 

### ISSUE THREAD

**Issue by zamvar** [CodeMinion/another_brother#22]
Hi i am using the example given here https://github.com/CodeMinion/Demo-Another-Brother-Prime

The official Brother Label App discovers my printer.

but the demo returns nothing.

This is what im getting on the example.

E/A-Brother(20700): Printers: [Lcom.brother.ptouch.sdk.NetPrinter;@1fcfe26
E/A-Brother(20700):  Out Printers: []

am i missing some configuration or is this printer not supported  by this plugin ?

**Comment by zamvar** [comment]
Is it possible its caused by this ? 
![image](https://user-images.githubusercontent.com/20177817/165518865-b3aa6fb1-7878-433a-bda4-e0a7813837b3.png)
found it in the PrinterInfo Model

**Comment by CodeMinion** [comment]
Hi @zamvar ! 

Thanks for reaching out about this. Could I trouble you to share the code you are using?

Thanks in advance!

**Comment by zamvar** [comment]
Closed the issue i think i may have missed something.
