### ISSUE TITLE
Github actions setup

### ISSUE THREAD

**Issue by BentEngbers** [CodeMinion/another_brother#24]
Hi @CodeMinion,

Would you be interested in a Github actions CI setup, for flutter formatting, analysing and building?
I would be happy to create a PR for this, and Github actions for opensource projects is [free](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/).
Maybe we could even incorporate a tool such as [renovatebot](https://www.mend.io/free-developer-tools/renovate/) (which i am more familliar with)  or [dependabot](https://github.com/dependabot).

Let me know if you would consider such a PR.

**Comment by CodeMinion** [comment]
Hey @BentEngbers ! 

Thanks for the offer it is really kind of you! Currently the repo is small enough that I don't have a new for CI but will definitely keep it in mind if it expands.

Thanks again!
