### ISSUE TITLE
iOs Bluetooth print not working

### ISSUE THREAD

**Issue by balanpaul** [CodeMinion/another_brother#27]
Hi, 
I am using this package and when I am trying to connect to TD-4550DNWB via Bluetooth, I received the following error: 

`2022-08-16 19:50:44.753563+0100 Runner[2215:316019] ERROR - could not find protocolID for protocolString com.brother.ptcbp
2022-08-16 19:50:44.753684+0100 Runner[2215:316019] ERROR - /Library/Caches/com.apple.xbs/Sources/ExternalAccessory/ExternalAccessory-410.100.2/EASession.m:-[EASession dealloc] - 212 unable to close session for _accessory=0x0 and sessionID=65536
2022-08-16 19:50:44.753735+0100 Runner[2215:316019] creating session failed`

Can you please help me?

Thank you so much in advance!

**Comment by CodeMinion** [comment]
Hello @balanpaul ! 

Thanks for reaching out about this. Could I trouble you to check if you have added the changes to your info.plist outlined here? https://pub.dev/packages/another_brother#ios-infoplist

Also what iOS device are you testing this on?

Thanks in advance!

**Comment by balanpaul** [comment]
Hey @CodeMinion,

Yes, the info.plist is correct, I also cloned your repository(https://github.com/CodeMinion/Demo-Another-Brother-Prime) and I received the same error.

I am using to test: 
- iPhone XS, with iOs 14.8.1 
- printer model: TD-4550DNWB

And for development I am using:
- Flutter (Channel stable, 3.0.5)
- Dart version 2.17.6
- XCode version 13.4.1
- package: another_brother: ^0.0.27 from pub.dev

Thank you very much!

**Comment by CodeMinion** [comment]
Anytime @balanpaul ! Thanks for the additional details!

I took a look at the Demo-Another-Brother-Prime project and it looks like that one does not have the info.plist updates. I'll send an update for it tonight. 

Could I trouble you to share you info.list to double confirm that it is inside the right section **UISupportedExternalAccessoryProtocols** and also the section of code from another_brother you are using to connect to the printer? 

Thanks in advance!

**Comment by balanpaul** [comment]
Hi @CodeMinion ,

Yes, i double check with find in files.

This is my plist file:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
   <key>CFBundleDevelopmentRegion</key>
   <string>$(DEVELOPMENT_LANGUAGE)</string>
   <key>CFBundleDisplayName</key>
   <string>[name]</string>
   <key>CFBundleExecutable</key>
   <string>$(EXECUTABLE_NAME)</string>
   <key>CFBundleIdentifier</key>
   <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
   <key>CFBundleInfoDictionaryVersion</key>
   <string>6.0</string>
   <key>CFBundleName</key>
   <string>[bname]</string>
   <key>CFBundlePackageType</key>
   <string>APPL</string>
   <key>CFBundleShortVersionString</key>
   <string>$(FLUTTER_BUILD_NAME)</string>
   <key>CFBundleSignature</key>
   <string>????</string>
   <key>CFBundleVersion</key>
   <string>$(FLUTTER_BUILD_NUMBER)</string>
   <key>LSRequiresIPhoneOS</key>
   <true/>
   <key>NSBluetoothAlwaysUsageDescription</key>
   <string>Please allow Bluetooth access to proceed further.
   </string>
   <key>NSBluetoothPeripheralUsageDescription</key>
   <string>Please allow Bluetooth access to proceed further.</string>
   <key>NSBonjourServices</key>
   <array>
      <string>_ipp._tcp</string>
      <string>_printer._tcp</string>
      <string>_pdl-datastream._tcp</string>
   </array>
   <key>NSLocalNetworkUsageDescription</key>
   <string>Allow access to find and connect to the Brother printer hardware via Network.</string>
   <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
   <string>Need Location permission</string>
   <key>NSLocationAlwaysUsageDescription</key>
   <string>Need Location permission</string>
   <key>NSLocationWhenInUseUsageDescription</key>
   <string>Need Location permission</string>
   <key>UIBackgroundModes</key>
   <array>
      <string>fetch</string>
      <string>remote-notifications</string>
   </array>
   <key>UILaunchStoryboardName</key>
   <string>LaunchScreen</string>
   <key>UIMainStoryboardFile</key>
   <string>Main</string>
   <key>UISupportedExternalAccessoryProtocols</key>
   <array>
      <string>com.brother.ptcbp</string>
      <string>com.issc.datapath</string>
   </array>
   <key>UISupportedInterfaceOrientations</key>
   <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
   </array>
   <key>UISupportedInterfaceOrientations~ipad</key>
   <array>
      <string>UIInterfaceOrientationPortrait</string>
      <string>UIInterfaceOrientationPortraitUpsideDown</string>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
   </array>
   <key>UIViewControllerBasedStatusBarAppearance</key>
   <false/>
   <key>CADisableMinimumFrameDurationOnPhone</key>
   <true/>
</dict>
</plist>`

**Comment by CodeMinion** [comment]
Thanks @balanpaul ! 

Normally the error "could not find protocolID for protocolString" on iOS means that the protocol string is not included under UISupportedExternalAccessoryProtocols but I can see you have it there. I also checked the prime example again and it also has it there which is also not working on your end. 

When trying to print are you tapping on the device under the apple settings to make sure it is connected first?

Also, could I trouble you to share the another_borther code you are using to print to this printer?

Thanks in advance!

**Comment by balanpaul** [comment]
Hello again @CodeMinion 

Yes, the device is connected and paired before I am trying to print.

This is printer setup and verify connection:

`
  var printInfo = PrinterInfo();

  var printer = new Printer();

  final UserBloc userBloc = BlocProvider.getBloc<UserBloc>();

  PrintBloc();

  Future<void> setupPrinter(String printerModel, [ACustomPaper? paper]) async {
    User? firebaseUser = FirebaseAuth.instance.currentUser;
    Map<String, dynamic>? claims =
        (await firebaseUser!.getIdTokenResult()).claims;

    printInfo.printMode = PrintMode.FIT_TO_PAGE;
    printInfo.isAutoCut = true;
    printInfo.printQuality = PrintQuality.DOUBLE_SPEED;
    printInfo.mirrorPrint = true;
    printInfo.pjDensity = 5;
    printInfo.rjDensity = 5;
    printInfo.binCustomPaper = paper;
    printInfo.printerModel = Model.TD_4550DNWB;

    if (userBloc.connectionType == ConnectionType.net) {
      printInfo.port = Port.NET;
      List<NetPrinter> printers =
          await printer.getNetPrinters([Model.TD_4550DNWB.getName()]);
      printInfo.ipAddress = printers.single.ipAddress;
      printInfo.macAddress = printers.single.macAddress;
    } else if (userBloc.connectionType == ConnectionType.bluetooth) {
      printInfo.port = Port.BLUETOOTH;
      List<BluetoothPrinter> printers =
          await printer.getBluetoothPrinters([Model.TD_4550DNWB.getName()]);
      printInfo.ipAddress = printers.single.macAddress;
    }
    await printer.setPrinterInfo(printInfo);

    if (await verifyStatus(printer)) {
      networkPrinter.add(printer);
    }
  }` 

And this is the code for printing 
`  Future<void> printPdfTicket(String pdf) async {
    if (!isNotNullPrinter()) {
      return;
    }

    await printer.printPdfFile(pdf, 1);
  }`

Thank you very much!

**Comment by balanpaul** [comment]
Thanks @CodeMinion !

I will try to use BLE and also I will try to test with a device which have o lower iOS version. I will come back with answer if it works or not.

Thank you again! Your package is really good overall!

**Comment by CodeMinion** [comment]
Happy to help @balanpaul ! 

Thanks! Keep me posted as to what you find!
