### ISSUE TITLE
[Ios] in latest xcode Version 14.0 (14A309) flutter build failed 

### ISSUE THREAD

**Issue by alihassan143** [CodeMinion/another_brother#32]
`Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/mac/Desktop/multi_vendor/ios/Pods/BRLMPrinterKit/BRLMPrinterKit/BRLMPrinterKit.framework/BRLMPrinterKit' for architecture arm64`

**Flutter Doctor**
```
flutter doctor

[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-x64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability```
i did all the configuration accordingly but alway xcode give error build faild when running in simulator

**Comment by CodeMinion** [comment]
Hi @alihassan143 ! Thanks for reaching out about this. Building to the iOS Simulator is not supported, so you'll need to build to a physical device. 

Please refer here for more info: https://github.com/CodeMinion/another_brother/issues/28

Thanks again!
