### ISSUE TITLE
getPDFFilePages - no implementation

### ISSUE THREAD

**Issue by lukesalter** [CodeMinion/another_brother#36]
HI,

I'm seeing this issue when trying to check the number of pages in my PDF file. Any chance you can take a look? I suspect it's just not a common method that's being used and something isn't right in the package somewhere.

`Unhandled Exception: MissingPluginException(No implementation found for method getPDFFilePages on channel another_brother)`

Looking forward to heard from you. I can do a while loop hunting for an ERROR_FILE_NOT_FOUND for now so it's not critical. It'd be nice to be able to do it the way brother intend.

Thanks for being so responsive on here - I've not been using the package (or flutter!) for long but I've got some faith in this.

**Comment by CodeMinion** [comment]
Hi @lukesalter,

Thanks for reaching out about this. I took a quick look and I can see we have an implementation for it on Android but not on iOS. Could you share what device(s) you are seeing this error on?

Thanks in advance,

**Comment by lukesalter** [comment]
Hi @CodeMinion, yes it's an iOS device. Is that something that the swift behind the scenes can't do or is it possible to get it working?

**Comment by CodeMinion** [comment]
Thanks for confirming @lukesalter. 

I took a quick look at the Brother iOS SDK and couldn't find a parallel call but let me reach out to them in case we are missing something and let you know what I find.

**Comment by CodeMinion** [comment]
Hi @lukesalter ,

I wanted to let you know that version 0.0.30 of another_brother now supports getPDFFilePages on iOS. 

I'll leave this open just in case you run into any trouble with it. So feel free to close it if all works out on your end. 

Thanks again for reaching out about this.

**Comment by lukesalter** [comment]
@CodeMinion perfect - this is great. I'll give it a spin later today and see how I get on. If it's all good I'll close this off.

**Comment by CodeMinion** [comment]
Thanks @lukesalter !
