### ISSUE TITLE
update the ios-no-type-b branch

### ISSUE THREAD

**Issue by BentEngbers** [CodeMinion/another_brother#37]
Hi @CodeMinion,

Could the ios-no-type-b branch be updated with the latest changes from main?
I tried to create the PR myself, but i lack the permissions.

**Comment by CodeMinion** [comment]
Hi @BentEngbers ! 

Thanks for reaching out about this. I just pushed the latest changes that bring in the Brother Android SDK v4.6.1 to the ios-no-type-b branch. 

Thanks also for the heads up on the permissions I'll take a look to see what's going on. 

Thanks again and don't hesitate to reach out if there is anything else I can help with.
