### ISSUE TITLE
Unsupported functions ios

### ISSUE THREAD

**Issue by gmorva-wunder** [CodeMinion/another_brother#45]
Hi,

I might be mistaken, but there seems to be quite a few functions that are only available for android.  
We're missing the following:
* `startPTTPrint`
* `flushPTTPrint`
* `removeTemplate`
* `transfer`

Is there a possibility for these functions to be available in the future, or is it some restriction on the Brother SDK end?

Thanks!

**Comment by CodeMinion** [comment]
Hi @gmorva-wunder !

Thanks for reaching out about this. Unfortunately the Android Brother SDK and iOS SDK currently used by another_brother don't have full feature parity with Android having more features overall as a result there might be some features not available in iOS yet. 

That said, I'll try to set some time aside this weekend to explore whether the absence of the functions listed is a result of missing APIs or just missing implementation in another_brother and let you know here. 

Thanks again,

**Comment by gmorva-wunder** [comment]
Hi @CodeMinion thanks for the fast response, I appreciate it!
