### ISSUE TITLE
iOS no-type-b not relevant for deploy

### ISSUE THREAD

**Issue by mikhael28** [CodeMinion/another_brother#53]
I recently deployed an application onto the Apple app store that used the standard drivers, without having to use ios-no-typeb branch. I had to manually submit the application to Brother, and pass along the application ID to apple during the review process, but afterwards was able to deploy to the app store normally. 

Sharing this, in case others are curious - as of May 2023, seems like Apple is okay with you deploying to the App Store with the brother drivers in their current state.

**Comment by CodeMinion** [comment]
Thanks for the details @mikhael28 . I suppose something might have changed on their end as until recently apps were getting rejected due to some missing binaries. 

Thanks again for sharing this!
