### ISSUE TITLE
Update Kotlin Gradle Version [Android]

### ISSUE THREAD

**Issue by anchals333** [CodeMinion/another_brother#54]
I'm using another_brother : 0.0.34 version & faced a kotlin gradle version issue.  

`FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50`

**Comment by CodeMinion** [comment]
Hi @anchals333 , 

Thanks for reaching out about this. Could you share a bit more details about your project? 

From the error it sounds like you are building using a newer version of Kotlin than currently available in another_brother.

Thanks in advance,

**Comment by anchals333** [comment]
@CodeMinion Here is project build.gradle : 

```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.15'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
Let me know if any other details are required.

**Comment by CodeMinion** [comment]
Thanks for the details @anchals333 ! 

It seems your Kotlin version is higher than the one supported in another_brother currently. One short term solution would be to lower your project's Kotlin version to match the one in another_brother.

Longer term there is a MR from the community to update to a more recent version of Kotlin but I will not have time to review it until later this month. Using that version in the meantime might also help.

Thanks again for the report,

**Comment by tomaspodmanicky** [comment]
How does it look with this issue? I cant lower my Kotlin version.

**Comment by CodeMinion** [comment]
Hi @anchals333 , @tomaspodmanicky ,

Version 2.0.0 of another_brother is now out on Pub.dev and it upgrades AGP to 7.3.0

Thanks again for the report,
