### ISSUE TITLE
Problem with dependency

### ISSUE THREAD

**Issue by Andre-Coelhoo** [CodeMinion/another_brother#57]
Hey everyone, I have added the another_brother: ^0.0.34 to my pub spec file but when trying to run even if I don't have any code of the package another_brother I get this error. Can anyone help me

Running Gradle task 'assembleDevDebug'...                       
../../.pub-cache/hosted/pub.dev/another_brother-0.0.34/lib/printer_info.dart:3300:53: Error: This expression has type 'void' and can't be used.
      FlutterBluePlus flutterBlue = FlutterBluePlus.instance;
                                                    ^
../../.pub-cache/hosted/pub.dev/another_brother-0.0.34/lib/printer_info.dart:3303:19: Error: The method 'startScan' isn't defined for the class 'FlutterBluePlus'.
 - 'FlutterBluePlus' is from 'package:flutter_blue_plus/flutter_blue_plus.dart' ('../../.pub-cache/hosted/pub.dev/flutter_blue_plus-1.10.9/lib/flutter_blue_plus.dart').
Try correcting the name to the name of an existing method, or defining a method named 'startScan'.
      flutterBlue.startScan(withServices: [Guid("A76EB9E0-F3AC-4990-84CF-3A94D2426B2B")], timeout: Duration(seconds: timeout~/1000));
                  ^^^^^^^^^
../../.pub-cache/hosted/pub.dev/another_brother-0.0.34/lib/printer_info.dart:3307:38: Error: The getter 'scanResults' isn't defined for the class 'FlutterBluePlus'.
 - 'FlutterBluePlus' is from 'package:flutter_blue_plus/flutter_blue_plus.dart' ('../../.pub-cache/hosted/pub.dev/flutter_blue_plus-1.10.9/lib/flutter_blue_plus.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'scanResults'.
      var subscription = flutterBlue.scanResults.listen((results) {
                                     ^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

**Comment by CodeMinion** [comment]
Hi @Andre-Coelhoo , 

Thanks for sharing this. Could I trouble you to post the output of your Flutter doctor? Also could you try performing a clean and building once more?

The version of flutter_blue_plus that we have in another_brother is 1.1.3 yet the logs show it as 1.10.9 so my first thought is that it might be caching related. 

Thanks in advance,

**Comment by Andre-Coelhoo** [comment]
sure here it is
andrecoelho@Air-de-Andre mobile-app-1 % fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E772610a darwin-arm64, locale en-US)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/andrecoelho/fvm/versions/3.7.11. Consider adding /Users/andrecoelho/fvm/versions/3.7.11/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

the first problem I think its because of the use of fem

**Comment by CodeMinion** [comment]
Hi @Andre-Coelhoo , glad to hear you got it working. 

Recently we had someone report something similar that seemed to be linked to having the wrong label but we couldn't reproduce it. Here is the link to that message https://github.com/CodeMinion/another_brother/issues/49#issuecomment-1564622436

**Comment by CodeMinion** [comment]
Hi @Andre-Coelhoo ,

Thanks again for reporting this. We just released another_brother v1.0.0 which updates the latest version of flutter_blue_plus . That version will resolve the 'This expression has type 'void' and can't be used.' issue you were seeing. 

Thanks again,
