### ISSUE TITLE
New bin papers for TD2125NWB

### ISSUE THREAD

**Issue by alaindeseine** [CodeMinion/another_brother#63]
Hi @CodeMinion,

I hope you're well.

I just got 2 new papers for the TD2125NWB printer.

- 57.2X31.8mm
- 57.2X50.8mm

You can find the bin files on my cloud: https://nc.cabinfo.eu/index.php/s/M7w4onfingPrMGG

If you can plan to add these new paper sizes to the library, that will be great!

Thanks in advance.

Sincerely

Alain Deseine

**Comment by CodeMinion** [comment]
Hi @alaindeseine ! 

Thanks for the new papers. I have added them to another_brother and published version 1.0.2 with them.

Could I trouble you to verify it all works well on your end?

Thanks again for your support,

**Comment by alaindeseine** [comment]
Hi @CodeMinion, 

I have successfully installed the 1.0.2 version of the lib and test with new label papers are just fine. So it's ok for me.

Sincerely, 

Alain Deseine.

**Comment by CodeMinion** [comment]
Perfect, thanks for all the support with this @alaindeseine !
