### ISSUE TITLE
Should specify minSdkVersion in readme

### ISSUE THREAD

**Issue by realrgt** [CodeMinion/another_brother#7]
Hi @CodeMinion, thank for the work delivered into this project you saved the day.
I think you'd have placed the `minSdkVersion 19` as a requisite. Thanks a lot!!

**Comment by CodeMinion** [comment]
Hi @realrgt ,

Glad you are enjoying the plugin and thanks for the heads up on the ReadMe. I have made the update and it will now display the minSDKVersion information. The information will also become available in the official pub page once we release the next version. 

Thanks again,
