### ISSUE TITLE
App crashes during attempt to print when another device is connected to the Bluetooth printer

### ISSUE THREAD

**Issue by devkumarkatta** [CodeMinion/another_brother#76]
I was trying to run my APK from android tablet, it worked fine initially but suddenly it started crashing while trying to print using QL820NWB on bluetooth, I discovered that my iPhone was paired and connected, when I disconnected my iPhone, problem was OK.  Question is if it is possible to have multiple devices paired and printing using this library ?

**Comment by CodeMinion** [comment]
Hi @devkumarkatta ,

Thanks for reaching out about this and apologies for the late reply. Could I trouble you to share the logs you see when the crash happens? 

Thanks in advance,
