### ISSUE TITLE
App Android build fails with error

### ISSUE THREAD

**Issue by iklochko** [CodeMinion/another_brother#77]
When building the app for Android, build is failing with log
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':another_brother:generateReleaseRFile'.
> Could not resolve all files for configuration ':another_brother:releaseCompileClasspath'.
   > Could not resolve com.brother.sdk:printer:4.6.1.
     Required by:
         project :another_brother
      > Could not resolve com.brother.sdk:printer:4.6.1.
         > Could not parse POM https://rouninlabs.jfrog.io/artifactory/rounin-libs-external/com/brother/sdk/printer/4.6.1/printer-4.6.1.pom
            > Already seen doctype.
   > Could not resolve com.brother.typeb:print:1.0.0.
     Required by:
         project :another_brother
      > Could not resolve com.brother.typeb:print:1.0.0.
         > Could not parse POM https://rouninlabs.jfrog.io/artifactory/rounin-libs-external/com/brother/typeb/print/1.0.0/print-1.0.0.pom
            > Already seen doctype.
```

When trying to access https://rouninlabs.jfrog.io/artifactory/rounin-libs-external/com/brother/sdk/printer/4.6.1/printer-4.6.1.pom, the page says that
`JFrog's Free-Tier subscription has been deactivated.`

**Comment by CodeMinion** [comment]
Hi @iklochko ,

Thanks for reaching out about this. It seems JFrog has ceased their open source project support and the hosted libraries are no longer available. 

We'll be looking for an alternative this weekend and be sure to let you know through here when it has been resolved. 

Thanks again,

**Comment by CodeMinion** [comment]
Hi @iklochko ,

Version 2.1.2 of another_brother is now available and it resolves the dependency issues you were seeing. I'll leave this ticket open for you to close once you have verified that it's all building for you. 

Thanks again for reaching out about this.

**Comment by iklochko** [comment]
@CodeMinion thank you for quick update. Will verify it during few days.
Any chance to do the same for no_type_b version?

**Comment by CodeMinion** [comment]
Hi @iklochko ,

Anytime, glad I could help. The same change has now been made to the ios-no-type-b branch. 

Someone reported that they did not have any rejections on the Apple store while using the main branch so you might not need it after all.

**Comment by iklochko** [comment]
Hi @CodeMinion 
Thank you for the update.
I would like to use main branch either, through I can not build it due to issues described [here](https://github.com/CodeMinion/another_brother/issues/10) in comments.

As for this particular issue, thank you again, I confirm it's resolved now.
