### ISSUE TITLE
App Android build fails with error #2

### ISSUE THREAD

**Issue by iklochko** [CodeMinion/another_brother#81]
When building the app for Android, build is failing with log

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':another_brother:generateReleaseRFile'.
* What went wrong:
Execution failed for task ':another_brother:generateReleaseRFile'.
> Could not resolve all files for configuration ':another_brother:releaseCompileClasspath'.
   > Could not resolve com.brother.sdk:printer:4.6.1.
     Required by:
         project :another_brother
      > Could not resolve com.brother.sdk:printer:4.6.1.
         > Could not get resource 'https://artifacts.rouninlabs.com/rounin-libs-external/com/brother/sdk/printer/4.6.1/printer-4.6.1.pom'.
            > Could not GET 'https://artifacts.rouninlabs.com/rounin-libs-external/com/brother/sdk/printer/4.6.1/printer-4.6.1.pom'.
               > Connect to artifacts.rouninlabs.com:443 [artifacts.rouninlabs.com/159.203.167.169] failed: Connection refused (Connection refused)
   > Could not resolve com.brother.typeb:print:1.0.0.
     Required by:
         project :another_brother
      > Could not resolve com.brother.typeb:print:1.0.0.
         > Could not get resource 'https://artifacts.rouninlabs.com/rounin-libs-external/com/brother/typeb/print/1.0.0/print-1.0.0.pom'.
            > Could not GET 'https://artifacts.rouninlabs.com/rounin-libs-external/com/brother/typeb/print/1.0.0/print-1.0.0.pom'.
               > Connect to artifacts.rouninlabs.com:443 [artifacts.rouninlabs.com/159.203.167.169] failed: Connection refused (Connection refused)

When trying to access https://artifacts.rouninlabs.com/rounin-libs-external/com/brother/sdk/printer/4.6.1/printer-4.6.1.pom, the browser says that
```
This site can’t be reachedartifacts.rouninlabs.com refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED
```

**Comment by CodeMinion** [comment]
Hi @iklochko ,

Thanks for the report. The error is due to our dependency server being down this past weekend it is now up and running once more. Try to build once again and you should be able to fetch those dependencies.

Don't hesitate to reach out if there is anything else we can help with,

**Comment by iklochko** [comment]
Hi @CodeMinion 
Seems like it's down again.

**Comment by CodeMinion** [comment]
Hi @iklochko ,

Thanks for the heads up. It should be up again. 

The status will also be available from now one here: http://status.rouninlabs.com/status/poachme

Thanks again and don't hesitate to reach out if there is anything else we can help with,

**Comment by iklochko** [comment]
@CodeMinion, check again please. Now server returns 502.

**Comment by mhanzla80** [comment]
@CodeMinion I am facing the same issue.
can you please guide us to fix it asap?

**Comment by CodeMinion** [comment]
Hi @mhanzla80 ,

The issue with the artifact server has now been resolved and is running once more. The status of the server is available at http://status.rouninlabs.com/status/poachme

Thanks again,
