### ISSUE TITLE
Could not resolve all files for configuration ':another_brother:debugCompileClasspath'.

### ISSUE THREAD

**Issue by sureshturbo** [CodeMinion/another_brother#82]
![image](https://github.com/CodeMinion/another_brother/assets/44191960/9f7acd51-8db7-4647-bead-afc0968ea20f)

**Comment by CodeMinion** [comment]
Hi @sureshturbo ,

Thanks for the report. The error is due to our dependency server being down this past weekend it is now up and running once more. Try to build once again and you should be able to fetch those dependencies. 

Don't hesitate to reach out if there is anything else we can help with,
