### ISSUE TITLE
Label format request

### ISSUE THREAD

**Issue by PrimaelQuemerais** [CodeMinion/another_brother#91]
Hello,

I'm trying to add support in my app for the TD-2125N but I would need the RD_W51H26mm label format for it.
I'm only seeing W57mm or W40_H40mm.

Would it be possible to add this format?

Thank you very much!

**Comment by CodeMinion** [comment]
Hi @PrimaelQuemerais ,

Thanks for reaching out about this. In order to add support for that paper we would need a .bin file generated for that printer and paper size. 

If you could send us a working bin file we can go ahead and update the library. 

Thanks again,

**Comment by PrimaelQuemerais** [comment]
Thank you for the quick reply!

I do not have the printer myself but I asked a colleague to generate one, I do not know if it is working. Here is a link to the generated files : https://drive.google.com/drive/folders/1FbhseM3ce6-vcggUw4cWznfuPBOo46SC?usp=share_link

Let me know if there is anything else I can help with.

**Comment by PrimaelQuemerais** [comment]
Hello!

Sorry for bumping this up, were you able to have a look?

Thank you so much for your time!

**Comment by CodeMinion** [comment]
Hi @PrimaelQuemerais ,

No apologies necessary. Version 2.1.7 has just been released with the bin paper you shared. Since I don't have a way to verify if the paper works I'll leave this issue open until we get confirmation from you that it's working correctly.

**Comment by PrimaelQuemerais** [comment]
Thank you so much @CodeMinion !

I will build a new version of our app tomorrow, have it tested and will let you know right away!

**Comment by PrimaelQuemerais** [comment]
Hi @CodeMinion !
So I had the new version tested and it doesn't work. The app crashes when trying to print using the new label.
I'm getting a TD-2125N delivered to me so I can generate a new bin file and test everything on my own.
I will keep you updated!

**Comment by CodeMinion** [comment]
Hi @PrimaelQuemerais !

Bummer about the failure but thanks for looking into it further. Don't hesitate to share the bin file ones you have it and we can go ahead and add it.

Thanks for the support,

**Comment by PrimaelQuemerais** [comment]
Hello @CodeMinion!
I just created a new pull request. I used a new bin file and was able to test with a TD2125N.
Everything seem to be working fine

**Comment by CodeMinion** [comment]
Hi @PrimaelQuemerais !

Thanks for testing and the fix. I have merged the changed and released version 2.1.8 to pub.dev. It should become available in 10 minutes or so for usage. 

Thanks again,

**Comment by PrimaelQuemerais** [comment]
Hello @CodeMinion
Thank you for the reactivity. I can confirm everything is working fine in the latest version.

Closing the issue now
