### ISSUE TITLE
Lack of Support for Brother DCP-T520W Printer

### ISSUE THREAD

**Issue by OsamaAyesh** [CodeMinion/another_brother#92]
Subject: Lack of Support for Brother DCP-T520W Printer

Dear pakage Owners,

I would like to inform you that our application is encountering issues with supporting the Brother DCP-T520W printer model. Current applications attempt to utilize printer libraries that support specific printer models, but our model does not align with them completely.

We urgently need to address support for this widely used printer model. Please provide technical support or guidance on how to resolve this issue at your earliest convenience.

Thank you very much for your understanding and cooperation.

Best regards,
Osama Ayesh
osayesh88@gmail.com
00970567450057

**Comment by CodeMinion** [comment]
Hi @OsamaAyesh ,

Thanks for reaching out about this. Unfortunately the printer you mention does not seem to be currently supported by the Brother mobile SDK (refer here for supported models https://support.brother.com/g/s/es/dev/en/mobilesdk/model/index.html?c=eu_ot&lang=en&navi=offall&comple=on&redirect=on) 

My recommendation is to submit an official request to Brother for the inclusion of that printer. Once a version version of the SDK is released we can go ahead and include the support in another_brother.

Thanks again,
