### ISSUE TITLE
Cannot print on PT-P300BTz

### ISSUE THREAD

**Issue by LacTQuan** [CodeMinion/another_brother#98]
Hello,
I am trying to write an app to print custom labels on PT-P300BT and PT-P300BTz but only the PT-P300BT is working at the moment.
After looking at the code, I realized that PT-P300BTz isn't in the source code of the plugin. I tried adding it into the source code (dart and ios native code) but it still doesn't work ("BRLMPrinterModelPT_P300BTz is not defined" when I try to build ipa, even though I have defined the new model in BRLMPrinterDefine.h)
Besides, do I need to modify anything in Android native code as I do not see any enum types in those Kotlin files.

Thank you so much.

**Comment by LacTQuan** [comment]
As far as I know, the current Brother SDK used for this package (4.6.1 on Android, and 4.6.4 on IOS) does not support this model (even the lastest SDK 4.9.1)

Correct me if I was wrong ~

**Comment by CodeMinion** [comment]
Hi @LacTQuan ,

Apologies for the delayed response. That seems correct as per my knowledge as well. Once this printers support is added to the native SDKs we can go ahead and include them so it might be a good opportunity for you to submit a request to Brother so they can consider adding support in their native SDKs.
